print-status: False

database:
    dialect: ${DATABASE_DIALECT:postgresql}
    username: ${DATABASE_USERNAME:test}
    password: ${DATABASE_PASSWORD:test}
    host: ${DATABASE_HOST:test}
    port: ${DATABASE_PORT:test}
    schema: ${DATABASE_SCHEMA:python_framework_test_schema}
    database: ${DATABASE_NAME:test}
    driver: ${DATABASE_DRIVER:psycopg2}

environment:
    logs:
        debug:
            key: DEBUG
            value: True
        warning:
            key: WARNING
            value: True
        wrapper:
            key: WRAPPER
            value: True
        log:
            key: LOG
            value: True
        info:
            key: LOG
            value: True
    database:
        # url:
        #     key: DATABASE_URL
        #     value: ${database.dialect}://${database.username}:${database.password}@${database.host}:${database.port}/${database.database}
        dialect:
            key: DATABASE_DIALECT
            value: ${database.dialect}
        username:
            key: DATABASE_USERNAME
            value: ${database.username}
        password:
            key: DATABASE_PASSWORD
            value: ${database.password}
        host:
            key: DATABASE_HOST
            value: ${database.host}
        port:
            key: DATABASE_PORT
            value: ${database.port}
        schema:
            key: DATABASE_SCHEMA
            value: ${database.schema}
        database:
            key: DATABASE_NAME
            value: ${database.database}
        driver:
            key: DATABASE_DRIVER
            value: psycopg2
    active-environment:
        key: ACTIVE_ENVIRONMENT
        value: local
    session:
        key: SESSION_SECRET
        value: test-key
    api-key:
        key: API_KEY_SECRET
        value: test-key
    security:
        key: SECURITY_SECRET
        value: test-key
