KW_JTI = 'jti'
KW_USER_CLAIMS = 'user_claims'
KW_IDENTITY = 'identity'
KW_FRESH = 'fresh'
KW_EXPIRATION = 'exp'
KW_NFB = 'nbf'
KW_IAT = 'iat'

KW_JWT_SECRET_KEY = 'JWT_SECRET_KEY'
KW_JWT_BLACKLIST_ENABLED = 'JWT_BLACKLIST_ENABLED'

UNAUTHORIZED_MESSAGE = 'Unauthorized'
FORBIDDEN_MESSAGE = 'Frobidden'

JWT_HEADER_NAME = 'JWT_HEADER_NAME'
JWT_HEADER_TYPE = 'JWT_HEADER_TYPE'

DEFAULT_JWT_AUTHORIZATION_HEADER_NAME = "Authorization"
DEFAULT_JWT_AUTHORIZATION_HEADER_TYPE = "Bearer"

DEFAULT_JWT_SESSION_HEADER_NAME = "Session"
DEFAULT_JWT_SESSION_HEADER_TYPE = "Bearer"
