from python_helper import Constant as c

REQUEST = 'Request'
RESPONSE = 'Response'

CONTROLLER_SPACE = f'[CONTROLLER]{c.SPACE}'
CLIENT_SPACE = f'[CLIENT] '

CONTROLLER_REQUEST = f'{CONTROLLER_SPACE}{REQUEST}'
CONTROLLER_RESPONSE = f'{CONTROLLER_SPACE}{RESPONSE}'
CLIENT_REQUEST = f'{CLIENT_SPACE}{REQUEST}'
CLIENT_RESPONSE = f'{CLIENT_SPACE}{RESPONSE}'
